#!/bin/bash
#see https://github.com/syp1975/playground
#template repository configuration

#repository config
PGSRC="https://raw.githubusercontent.com/syp1975/bash-src/main/"
PGPAT=""
PGEXTRA=""

#install/ubuntu-bootstrap script config
#UNWANTED_SERVICES=space-separated-list of services to disable
#UNWANTED_PACKAGES=space-separated-list of packages to remove
#WANTED_PACKAGES=space-separated-list of packages to install
#UNWANTED_MOTD=space-separated-list of motd modules in /etc/update-motd.d/ to disable
#WANTED_MOTD=space-separated-list of motd modules to download from repo into /etc/update-motd.d/, include trailing digits (NN-)
  #files can contain environment variables that will get replaced by its values before saving the file
#LOCALES=space-separated-list of locales to generate, first one will be selected as default. see /usr/share/i18n/locales
#CHARMAP=char encoding used to generate the locales and display text on the console. defaults to UTF-8. see /usr/share/i18n/charmaps
#CODESET=set of characters used to display text on the console. defaults to Uni2.  see man console-setup
#KB_LAYOUT=changes your keyboard layout. see /usr/share/X11/xkb/rules/xorg.lst.
#KB_VARIANT=changes your keyboard variant. see /usr/share/X11/xkb/rules/xorg.lst
#SSHD_PORT=if different than 22, enables endlessh tarpit on port 22/tcp and changes sshd listening port to this tcp port. Example: 2222
#SSHD_PUBKEY=if a public key is defined, enables pubkey authentication and disables password authentication.

#fail2ban/install script config
#FAIL2BAN_JAIL=initial jail.local file to download from the repo
#FAIL2BAN_ACTIONS=space-separated-list of files to download from the repo to the action.d folder
#FAIL2BAN_IGNORE=space-separated-list of cidr that fail2ban should ignore when a connecion is stablished
#files can contain environment variables that will get replaced by its values before saving the file

#install/telegram config
#TELEGRAM_CONF=path of the telegram.sh config file (~/.telegram.sh.conf or /etc/telegram.sh.conf)
#TELEGRAM_TOKEN=bot token
#TELEGRAM_CHAT=id of the chat
