#!/usr/bin/env bash
#install glow, a cli markdown viewer
if grep -qxF 'deb [trusted=yes] https://repo.charm.sh/apt/ /' /etc/apt/sources.list.d/charm.list; then
  echo >&2 -e "${YELLOW}Charm repository already added to apt sources.${NOFORMAT}"
else
  echo 'deb [trusted=yes] https://repo.charm.sh/apt/ /' | sudo tee /etc/apt/sources.list.d/charm.list > /dev/null
fi
sudo apt-get update -q
sudo apt-get install -qy glow
sudo apt-get clean -q
