#!/usr/bin/env bash
#install glow, cli markdown viewer
if grep -qxF 'deb [trusted=yes] https://repo.charm.sh/apt/ /' /etc/apt/sources.list.d/charm.list; then
  echo >&2 -e "${YELLOW}Charm repository already added to apt sources.${NOFORMAT}"
else
  echo 'deb [trusted=yes] https://repo.charm.sh/apt/ /' | tee /etc/apt/sources.list.d/charm.list
fi
apt-get update -q
apt-get install -qy glow
apt-get clean -q
