#!/usr/bin/env bash
#installs oracle cloud infraestructure cli
bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh) --accept-all-defaults"
if [ -z "$OCI_CONFIG_FILE" ]; then
  cat <<EOF >&2
Steps to configure:
In the browser, open oracle cloud administration console,
Navigate to Identity & Security > Users,
Create a user for oci cli access to your tenancy, either IDCS or local IAM user.
Add an API key.
Download private and public key files.
Upload private key to ~/.oci/oci_private_key.pem, set privacy permissions accordingly.
Copy config file contents and paste it in ~/.oci/config, setting the right path to the private key_file.
EOF
else
  echo >&2 -e "${BLUE}Downloading oci config file from \"$OCI_CONFIG\".${NOFORMAT}"
  params=()
  [ ! -z "$OCI_CONFIG_SRC" ] && params+=("@$OCI_CONFIG_SRC")
  pg "${params[@]}" cat "$OCI_CONFIG_FILE" > ~/.oci/config
  chmod 600 ~/.oci/config
  echo >&2 -e "${GREEN}Done.{NOFORMAT}"  
fi
